### ISSUE TITLE
Validator node names. geth-validator xrpl-validator

### ISSUE THREAD

**Issue by gmixoulis** [UNIC-IFF/blockchain-benchmarking-framework#4]

**Comment by antIggl** [comment]
@gmixoulis . Elaborate more on the description section of the issue.
It's also a good practice to label the issues according to their category and importance. For example, if the issue is a feature, add label feature. If it's a bug, label it as bug. If it's severe bug, that has a huge impact on the results and the operation of the project, label it as severe. You can add more than one labels for each issue. You can also add uncategorized label for issues you are not sure right now.

**Comment by gmixoulis** [comment]
Thank you for your advice! I will follow your advice for the next issues! This issue is about the validator node names of the different networks running on BBF, because they should be consistent. Thus it is not a bug actually, more like an enhancement. :)

**Comment by antIggl** [comment]
You haven't still completed the description of this issue. Have you agreed to a convention or you have just opened an issue without any proposal? 
One key contribution to this issue is to list the files you have to revise for it to work. :)

**Comment by mtouloup** [comment]
Fixed and closed
